### ISSUE TITLE
Bereitstellungsprofile für Erweiterungen erstellen?

### ISSUE THREAD

**Issue by Weptun** [MicrosoftDocs/IntuneDocs.de-de#39]
Wir stehen vor dem Problem zur Bereitstellung eine App mit dem IntuneMAMPackager Umschließen zu müssen. Eine wesentliche Funktionalität der App ist das öffnen von Dateien in einem eigenen Format. Beim Umschließen bekommen wir folgende Meldung angezeigt:
"WARNUNG: Diese Anwendung unterstützt das Öffnen mindestens eines Dateityps, verfügt aber nicht über die geeigneten Berechtigungen für die Unterstützung durch die Intune-App. Mithilfe des Befehlszeilenarguments "-x" muss ein zusätzliches Bereitstellungsprofil angegeben werden. Dieses Profil muss einen Platzhalteranwendungsbezeichner oder den Anwendungsbezeichner "${PRODUCT_BUNDLE_IDENTIFIER}.IntuneOpenInAction" umfassen und mindestens eine Anwendungsgruppe enthalten, die gemeinsam mit der Hauptanwendung verwendet wird. Wenn dieses Profil nicht angegeben wird, können andere Intune-App-fähige Anwendungen keine Dateien an diese Anwendung senden."

Konstellation:
- Wir sind Entwickler einer App die Dateien in einem speziellen Format öffnen kann
- Unser Auftraggeber hat uns beauftragt für einen seiner Kunden die App bereit zu stellen
- Dieser Kunde verwendet Intune um Apps InHouse bereit zu stellen und die Dateien werden über OneDrive verteilt

Während die App unter normalen Bedingungen einwandfrei funktioniert kann der Kunde die Dateien mit "aktivierten Policies" nicht öffnen (bzw. an die App senden).

Wie helfen wir dem Kunden uns die nötigen Informationen zur Verfügung zu stellen um die Warnung zu beseitigen?
- Wo findet der Kunde die nötige "Anwendungsgruppe" die in unserer App hinterlegt werden muss?
- Wie erzeugt der Kunde das Bereitstellungsprofil das die nötigen Berechtigungen enthält?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a89dd12d-a959-9685-2994-9a2fb40abcc8
* Version Independent ID: 89738826-6064-efb6-d97a-cbac750d3a8b
* Content: [Umschließen von iOS-Apps mit dem Intune App Wrapping Tool](https://docs.microsoft.com/de-de/intune/app-wrapper-prepare-ios#feedback)
* Content Source: [intune/app-wrapper-prepare-ios.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune/app-wrapper-prepare-ios.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by LisandroSu** [comment]
Hallo, @Weptun 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
