### ISSUE TITLE
0 von 10 Punkten

### ISSUE THREAD

**Issue by jasc76** [MicrosoftDocs/IntuneDocs.de-de#41]
Alles gelöscht und von vorne, geht immer noch nicht.
er sagt immer noch er könnte das mail profil nicht hinzufügen
Wirklich Schlecht programmiert das ganze. Früher hat das mal gut funktioniert aber mittlerweile ist dieser ganze Prozess einfach nur noch sinnlos kompliziert und buggy

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bf9f3f90-c272-97cc-cc4e-367628358303
* Version Independent ID: 29e86a5c-cdd4-a4e6-8af1-2571b1faa96b
* Content: [Es wurde ein vorhandenes geschäftliches E-Mail-Konto gefunden](https://docs.microsoft.com/de-de/intune-user-help/existing-company-email-account-found#feedback)
* Content Source: [intune-user-help/existing-company-email-account-found.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune-user-help/existing-company-email-account-found.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by CeciAc** [comment]
Hallo, @jasc76 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
