### ISSUE TITLE
I dont have a fucking corporate mail account on this device

### ISSUE THREAD

**Issue by jasc76** [MicrosoftDocs/IntuneDocs.de-de#42]
I deleted it

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bf9f3f90-c272-97cc-cc4e-367628358303
* Version Independent ID: 29e86a5c-cdd4-a4e6-8af1-2571b1faa96b
* Content: [Es wurde ein vorhandenes geschäftliches E-Mail-Konto gefunden](https://docs.microsoft.com/de-de/intune-user-help/existing-company-email-account-found)
* Content Source: [intune-user-help/existing-company-email-account-found.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune-user-help/existing-company-email-account-found.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by CeciAc** [comment]
Hello, @jasc76 

Your comments are in violation of our code of conduct on https://opensource.microsoft.com/codeofconduct/. 
For this reason, we have to lock and close this issue.

Kind regards,
Microsoft DOCS International Team
