### ISSUE TITLE
Test Feedback, please ignore

### ISSUE THREAD

**Issue by bodhigautam** [MicrosoftDocs/IntuneDocs.de-de#46]
Testing. Please ignore

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1b6d8285-902e-e3b2-937b-cbdf86107bf5
* Version Independent ID: a78bcea6-7109-a3e1-7c45-e557a1b31560
* Content: [Microsoft Intune – Azure](https://docs.microsoft.com/de-de/intune/fundamentals/what-is-intune)
* Content Source: [intune/fundamentals/what-is-intune.md](https://github.com/MicrosoftDocs/IntuneDocs.de-de/blob/live/intune/fundamentals/what-is-intune.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by srvbpigh** [comment]
Hello, @bodhigautam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
